Add query param to filter decisions by scenarios
crowdsecurity/crowdsec pull request #1294
Opened 2022-02-28 11:46 UTC by sbs2001

Eg usage:

`http://localhost:8080/v1/decisions/stream?startup=true&scenarios_not_containing=ssh,path,files`
`http://localhost:8080/v1/decisions/stream?startup=true&scenarios_containing=http,bf`

2022-02-28 12:10 UTC, buixor reviewed
Thanks ! I think we need as well :
 - to update the swagger
 - to update the client library
 - to see needed changes in the bouncers as you changed `scope` to `scopes`

2022-03-15 13:29 UTC, buixor commented
@sbs2001 : the tests for this one broke. Let me know when fixed so we can merge it.

2022-03-16 11:01 UTC, he2ss requested changes

2022-03-16 11:01 UTC, he2ss commented on pkg/apiserver/decisions_test.go
Hi @sbs2001,

I sent you a pm about this PR. 
For information, you just need to add the unittest about the new filters that are missing.

2022-03-16 13:34 UTC, he2ss approved these changes

2022-03-16 13:37 UTC, merged