Memory check for cscli dashboard setup
crowdsecurity/crowdsec pull request #1513
Opened 2022-05-07 17:06 UTC by LaurenceJJones

If total memory < 1GB and force-yes is not provided the user can answer Y/n to continue running the Metabase container if the force-yes flag is provided it will just warn the user that Metabase container requires 1-2GB

Please note the current calculation of memory is set to 1GB as per issue, however, in crowdsec documentation it states 1-2GB

#826

2022-05-07 18:17 UTC, LaurenceJJones commented on cmd/crowdsec-cli/dashboard.go
> +	if uint64(math.Pow(2, 30)) >= totMem {
Don't know math.Pow is needed here as the value will always resolve to ```1073741824``` so we could swap this out and hard code the value

2022-05-09 10:58 UTC, buixor requested changes
minor suggestion, overall lgtm :+1:

2022-05-09 10:58 UTC, buixor commented on cmd/crowdsec-cli/dashboard.go
> +						log.Fatalf("unable to ask about RAM check: %s", err)
we might want to warn/error on this but not fatal : if for any reason the check errors, we're preventing the user from setting up the dashboard

2022-05-17 12:22 UTC, he2ss approved these changes
lgtm

2022-05-18 09:05 UTC, merged