Blackhole new behaviour and add support for WAL when using sqlite
crowdsecurity/crowdsec pull request #1708
Opened 2022-08-08 10:52 UTC by blotus

- Allow to enable WAL when using sqlite
 - Change `blackhole` behaviour: previously, a bucket would have been created even if the overflow would be discarded in the end. This could lead to a lot of useless buckets being created and tracked.
 
The new behaviour prevents the bucket creation if the scenario is blackholed.
 
This slightly change the meaning of blackhole: before, a new bucket would be created, events poured to it, if the blackhole expired before it was full enough to overflow, it would be allowed to overflow normally.
Now, the bucket will not be created in the first place, which means that some overflows that would have happened with the old behaviour will not happen now (this is likely not an issue in real life).

2022-08-10 20:32 UTC, ornicar commented
We (lichess.org) are running this in production right now. I'll report if anything unexpected happens.

2022-08-16 11:44 UTC, buixor commented
let's make blackhole cleanup rely on latest event's timestamp

2022-08-16 11:46 UTC, buixor requested changes
let's make blackhole cleanup rely on latest event's timestamp

2022-08-18 06:13 UTC, buixor commented on cmd/crowdsec/crowdsec.go
> +	if !cConfig.Crowdsec.BucketsGCEnabled {
it's a bit counter-intuitive, might be worth a comment ;)

2022-08-18 10:12 UTC, buixor approved these changes
lgtm

2022-08-26 11:34 UTC, sabban commented
Test needed to be merged.

2022-11-25 13:10 UTC, closed without merging