Add Kubernetes audit acquisition
crowdsecurity/crowdsec pull request #1767
Opened 2022-09-26 10:19 UTC by blotus

- Add Kubernetes audit logs acquisition by exposing a webhook
 - Add `UnmarshalJSON` and `UnmarshalXML` helpers to unmarshal a log line during parsing, removing the need to call `JSONExtract` each time we want to get a field from a JSON string
 - Add `GetMeta`  function in go template to allow for easier meta retrieval in notification templates
 - Update `expr` version to add support for NilSafe getters

2022-10-03 08:28 UTC, wojtekxtx requested changes
Fix errors ( see #1767 ) as well as merging conflicts

2022-11-21 13:18 UTC, buixor reviewed
minor feedback, overall look good. Question as discussed : do we want the HTTP listener to be generic now or later ?

2022-11-21 13:18 UTC, buixor commented on pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
> +			Src:     fmt.Sprintf("%s:%d", ka.config.ListenAddr, ka.config.ListenPort),
can we keep track of the real source ? (ip and src port for ex)

2022-12-02 16:53 UTC, buixor approved these changes
just a suggestion on having a debug level for this, otherwise LGTM

2022-12-02 16:53 UTC, buixor commented on pkg/acquisition/modules/kubernetesaudit/k8s_audit.go
> +	ka.logger.Tracef("webhookHandler receveid: %s", string(jsonBody))
shouldn't we have a `.Debugf` version ? Might be useful to debug the datasource ?

2022-12-06 09:54 UTC, mmetc approved these changes

2022-12-06 12:47 UTC, merged