Stream decisions from db
crowdsecurity/crowdsec pull request #1927
Opened 2022-12-12 18:02 UTC by blotus

When querying `/decisions/stream`, write the decisions as soon as possible to the client.

This allows to greatly reduce the memory usage of crowdsec in some "extreme" situations (eg, lots of bouncers querying LAPI at the same time to get a lot of decisions).

For comparison with the master branch, with around 300k decisions in the database and 100 bouncers (ie, 100 requests in parallel to `/decisions/stream?startup=true`):
 - Master: Crowdsec used around 44G of RAM (and apparently never released it)
 - This PR: With a page size of 10k (configurable in a future commit), memory usage never goes above 1G.
 
 Response time is around the same as before for startup request (if not a little bit faster), but for delta requests it seems to be quite longer (1ms -> 150ms, still under investigation).

2023-01-04 10:35 UTC, buixor requested changes
PR looks cool to me. Some minor cleanup (comments) to do. Should we put this behind a feature flag ?

2023-01-31 10:58 UTC, buixor requested changes
can you FF it plz

2023-02-20 09:10 UTC, blotus commented
/kind enhancement
/area lapi

2023-02-20 14:25 UTC, mmetc approved these changes

2023-02-20 14:26 UTC, merged