Auto detect if reading logs or storing sqlite db on a network share
crowdsecurity/crowdsec pull request #2241
Opened 2023-05-29 12:52 UTC by blotus

2023-05-29 12:52 UTC, blotus commented
/kind fix

2023-07-25 07:53 UTC, buixor requested changes
moar explicit logging

2023-07-25 07:53 UTC, buixor commented on pkg/acquisition/modules/file/file.go
> +				inotifyPoll = false
Is this worth explicit logging ? "Disabling inotify poll on %s as it is a network share. You can manually set inotify to false to make this message disappear, or to true to enforce inotify poll"

2023-07-25 07:53 UTC, buixor commented on pkg/csconfig/database.go
> +			}
same as above, we want logging if we override the users parameters based on our detection :)

2023-07-25 12:00 UTC, buixor approved these changes

2024-02-23 14:03 UTC, mmetc commented
@blotus conflicts are fixed, keep in mind that on master we don't care about at all (no warning, no check) about WAL from cscli. I kept the same behavior in this PR.

2024-03-07 13:04 UTC, merged