update libsystemd in debian docker image
crowdsecurity/crowdsec pull request #2245
Opened 2023-05-30 15:26 UTC by he2ss

* fix https://github.com/crowdsecurity/crowdsec/issues/2217

2023-05-30 15:27 UTC, AlteredCoder approved these changes

2023-05-31 07:54 UTC, he2ss commented
/kind dependencies

2023-05-31 09:34 UTC, mmetc requested changes

2023-05-31 09:34 UTC, mmetc commented on Dockerfile.debian
> +RUN echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list \
this is not required in the build stage

2023-05-31 10:19 UTC, mmetc approved these changes

2023-05-31 10:39 UTC, merged