add api push to crowdsec
crowdsecurity/crowdsec pull request #236
Opened 2020-09-18 15:02 UTC by AlteredCoder

2020-09-18 15:35 UTC, registergoofy approved these changes
LGTM

2020-09-21 16:18 UTC, buixor requested changes
wip

2020-09-21 16:18 UTC, buixor commented on cmd/crowdsec/output.go
> +	if len(dedupCache) != len(alerts) {
I think we should make this debug (it was my own debug :<)

2020-09-21 16:18 UTC, buixor commented on cmd/crowdsec/output.go
> +		Scenarios: []string{"aaaaaa", "bbbbb"},
we need to use the method to get the list of enabled scenarios

2020-09-21 16:18 UTC, buixor commented on cmd/crowdsec/output.go
> +				cacheMutex.Unlock()
we can move the unlock before the pushAlerts to avoid locking the routine during the long operation

2020-09-21 16:18 UTC, buixor commented on cmd/crowdsec/output.go
> -			log.Infof("Flushing outputs")
here we will need to push as well pending signals

2020-09-21 16:18 UTC, buixor commented on cmd/crowdsec/output.go
> +			if cConfig.Crowdsec.SimulationConfig.Simulation != nil && *cConfig.Crowdsec.SimulationConfig.Simulation {
`if cConfig.Crowdsec.SimulationConfig.Simulation != nil && *cConfig.Crowdsec.SimulationConfig.Simulation {` -> `if cConfig.Crowdsec.SimulationConfig != nil && ...` no ?

2020-09-22 15:01 UTC, registergoofy approved these changes
lgtm

2020-09-22 15:02 UTC, registergoofy approved these changes

2020-09-22 15:18 UTC, merged