Add version override and update
crowdsecurity/crowdsec pull request #2370
Opened 2023-07-21 15:42 UTC by LaurenceJJones

2023-07-21 15:43 UTC, LaurenceJJones commented
/kind enhancement
/area cscli

2023-07-21 16:06 UTC, LaurenceJJones commented
Link to #2369 but adds cscli flag to override version so users are not hardcoded to a single version

2023-07-23 21:10 UTC, mmetc commented
Two things - 

1 - the name of the variable would be metabaseVersion, not metabaseDefaultVersion

2 - we should let the user override metabaseImage string instead

2023-07-23 21:18 UTC, LaurenceJJones commented
> Two things - 
> 
> 1 - the name of the variable would be metabaseVersion, not metabaseDefaultVersion

Agree

> 
> 2 - we should let the user override metabaseImage string instead

I disagree that the user should be able to pass the whole image name as if an admin allows the user to run as sudo they will be able to run any container

2023-07-23 21:27 UTC, mmetc commented
> > 2 - we should let the user override metabaseImage string instead
> 
> I disagree that the user should be able to pass the whole image name as if an admin allows the user to run just cscli as sudo they will be able to run any container

which can be done already with cscli explain

2023-07-24 08:06 UTC, blotus requested changes
Looks mostly ok to me, but as @mmetc said, the user should be able to override the whole image. (I don't really consider this to be a security risk if they have sudo for cscli, as they can already execute arbitraty commands as root easily).

2023-07-24 08:06 UTC, blotus commented on cmd/crowdsec-cli/dashboard.go
> +	cmdDashSetup.Flags().StringVarP(&metabaseDefaultVersion, "version", "v", metabaseDefaultVersion, "Metabase version to use")
`metabaseDefaultVersion` should be `metabaseVersion`

2023-07-25 13:10 UTC, blotus approved these changes

2023-07-25 13:21 UTC, merged