Appsec: properly populate event
crowdsecurity/crowdsec pull request #2943
Opened 2024-04-15 11:46 UTC by blotus

2024-04-15 16:19 UTC, buixor commented
/area appsec
/kind enhancement

2024-05-14 10:11 UTC, LaurenceJJones commented
private ip:

```
root@bookworm:/opt/crowdsec# cscli alerts inspect 2 -d

################################################################################################

- ID           : 2
- Date         : 2024-05-14T10:02:38Z
- Machine      : c90cca144e044e6297dded898a0e76da
- Simulation   : false
- Reason       : crowdsecurity/vpatch-env-access
- Events Count : 0
- Scope:Value  : Ip:192.168.121.1
- Country      :
- AS           :
- Begin        : 2024-05-14 10:02:38 +0000 UTC
- End          : 2024-05-14 10:02:38 +0000 UTC
- UUID         : a31a4bd3-233c-42a1-93bb-d14143718a97


- Context  :
╭───────────────┬──────────────────╮
│      Key      │      Value       │
├───────────────┼──────────────────┤
│ matched_zones │ REQUEST_FILENAME │
│ method        │ GET              │
│ target_uri    │ /.env            │
╰───────────────┴──────────────────╯

- Events  :

- Date: 2024-05-14 10:02:38 +0000 UTC
╭───────────────┬─────────────────────────────────╮
│      Key      │              Value              │
├───────────────┼─────────────────────────────────┤
│ id            │ 3256131465                      │
├───────────────┼─────────────────────────────────┤
│ matched_zones │ REQUEST_FILENAME                │
├───────────────┼─────────────────────────────────┤
│ method        │ GET                             │
├───────────────┼─────────────────────────────────┤
│ msg           │ crowdsecurity/vpatch-env-access │
├───────────────┼─────────────────────────────────┤
│ name          │ crowdsecurity/vpatch-env-access │
╰───────────────┴─────────────────────────────────╯
```

fake public test:
```

################################################################################################

- ID           : 3
- Date         : 2024-05-14T10:10:52Z
- Machine      : c90cca144e044e6297dded898a0e76da
- Simulation   : false
- Reason       : crowdsecurity/vpatch-env-access
- Events Count : 0
- Scope:Value  : Ip:1.2.3.4
- Country      : AU
- AS           :
- Begin        : 2024-05-14 10:10:52 +0000 UTC
- End          : 2024-05-14 10:10:52 +0000 UTC
- UUID         : 07a8cd55-b9d3-46f4-a5ad-217ae9ad9d5b


- Context  :
╭───────────────┬──────────────────╮
│      Key      │      Value       │
├───────────────┼──────────────────┤
│ matched_zones │ REQUEST_FILENAME │
│ method        │ GET              │
│ target_uri    │ /.env            │
╰───────────────┴──────────────────╯

- Events  :

- Date: 2024-05-14 10:10:52 +0000 UTC
╭───────────────┬─────────────────────────────────╮
│      Key      │              Value              │
├───────────────┼─────────────────────────────────┤
│ id            │ 3256131465                      │
├───────────────┼─────────────────────────────────┤
│ matched_zones │ REQUEST_FILENAME                │
├───────────────┼─────────────────────────────────┤
│ method        │ GET                             │
├───────────────┼─────────────────────────────────┤
│ msg           │ crowdsecurity/vpatch-env-access │
├───────────────┼─────────────────────────────────┤
│ name          │ crowdsecurity/vpatch-env-access │
╰───────────────┴─────────────────────────────────╯
```

2024-05-24 10:18 UTC, buixor commented on pkg/acquisition/modules/appsec/utils.go
> +				evtRule.Meta = appendMeta(evtRule.Meta, key, value)
we need to ensure this gets properly stripped if it's too long

2024-05-24 11:22 UTC, buixor requested changes
we should ensure that meta are stripped if too long (otherwise they will cause endess retry loop), otherwise lgtm.

2024-05-27 08:04 UTC, buixor approved these changes

2024-05-27 08:15 UTC, merged