Add alert by id api
crowdsecurity/crowdsec pull request #375
Opened 2020-11-05 20:33 UTC by AlteredCoder

- Added new route in LAPI : `GET /v1/alerts/:alert_id`
- Added possibility to specify args for `cscli alerts list <alert_id>` : 

```bash
$ sudo cscli alerts list 191

################################################################################################

 - ID         : 191
 - Date       : 2020-10-21T14:39:15Z
 - Machine    : N/A
 - Simulation : false
 - Reason     : crowdsecurity/ssh-bf
 - Scope:Value: Ip:218.92.0.200
 - Country    : CN
 - AS         : No.31,Jin-rong Street

 - Decisions  :
+-----+-----------------+--------+-----------------------+----------------------+
| ID  |   SCOPE:VALUE   | ACTION |      EXPIRATION       |      CREATED AT      |
+-----+-----------------+--------+-----------------------+----------------------+
| 191 | Ip:218.92.0.200 | ban    | -363h49m29.649915349s | 2020-10-21T14:39:15Z |
+-----+-----------------+--------+-----------------------+----------------------+

 - Events  :

- Date: 2020-10-21 14:39:14 +0000 UTC
+-------------+-----------------------+
|     KEY     |         VALUE         |
+-------------+-----------------------+
| ASNOrg      | No.31,Jin-rong Street |
| log_type    | ssh_failed-auth       |
| source_ip   | 218.92.0.200          |
| IsoCode     | CN                    |
| IsInEU      | false                 |
| ASNNumber   |                  4134 |
| target_user | root                  |
| service     | ssh                   |
| SourceRange | 218.92.0.0/17         |
+-------------+-----------------------+
```

2020-11-05 21:06 UTC, erenJag commented
* Maybe the display of each event can be little noisy in output. 
* Why not having `cscli alerts list -id <ID>` ?

2020-11-06 08:34 UTC, buixor requested changes

2020-11-06 08:34 UTC, buixor commented on cmd/crowdsec-cli/alerts.go
> +cscli alerts list <alert_id>
this one needs to be removed, moved in a separate command

2020-11-06 08:43 UTC, buixor commented on cmd/crowdsec-cli/alerts.go
> +cscli alerts list <alert_id>
self fix

2020-11-06 08:44 UTC, buixor approved these changes
lgtm

2020-11-06 08:49 UTC, merged