Geoip
crowdsecurity/crowdsec pull request #585
Opened 2021-01-20 20:47 UTC by registergoofy

take care of the new geoip collection

2021-01-21 07:09 UTC, erenJag requested changes

2021-01-21 07:09 UTC, erenJag commented on wizard.sh
> +geoip_workaround() {
not very clear as a function name.

2021-01-21 07:09 UTC, erenJag commented on wizard.sh
> +	    log_info "Prout "
review the logging content please :)

2021-01-21 07:09 UTC, erenJag commented on wizard.sh
> +	    log_info "Prout 3"
here too

2021-01-21 07:09 UTC, erenJag commented on wizard.sh
> +	    log_info "Prout 4"
Same here

2021-01-25 11:35 UTC, buixor commented
deprecated, we're going to issue debian-specific patch to deal with this

2021-01-25 11:35 UTC, closed without merging