create crowdsec group for metabase and crowdsec.db
crowdsecurity/crowdsec pull request #606
Opened 2021-02-05 14:24 UTC by AlteredCoder

2021-02-05 14:55 UTC, registergoofy approved these changes
lgtm

2021-02-06 20:05 UTC, buixor requested changes

2021-02-06 20:05 UTC, buixor commented on cmd/crowdsec-cli/dashboard.go
> +					Message: fmt.Sprintf("We need to add a new group called '%s' to the system, is it ok for you ?", crowdsecGroup),
we need a more explicit message, ie. "for metabase docker to be able to access SQLite file, we need to add a group called ..."

2021-02-06 20:05 UTC, buixor commented on cmd/crowdsec-cli/dashboard.go
> +			if !answer && !forceYes {
I don't think we want to fatal here (ie. user can do it on its own), but rather a strong warning

2021-02-06 20:05 UTC, buixor commented on cmd/crowdsec-cli/dashboard.go
> +				if err := groupDel.Run(); err != nil {
I don't think we want to fatal if the group wasn't deleted

2021-02-10 08:23 UTC, buixor approved these changes
lgtm

2021-02-10 08:23 UTC, merged