pkg/apiclient: pick up dropped errors
crowdsecurity/crowdsec pull request #676
Opened 2021-03-11 02:45 UTC by alrs

This fails locally, perhaps it will do better in CI.

2021-03-11 10:08 UTC, AlteredCoder requested changes

2021-03-11 10:08 UTC, AlteredCoder commented on pkg/apiclient/auth_test.go
> +	require.NoError(t, err)
the CI fail because this test must return an error. As you can see below, we check that the error message contains `APIKey is empty`.

2021-03-11 10:09 UTC, AlteredCoder commented
Hello @alrs,

Thanks for your contribution. I think that if you fix my comment, the CI will pass :)

2021-03-15 19:59 UTC, alrs commented
Should be good, @AlteredCoder, lmk if you see anything else.

2021-03-17 11:36 UTC, AlteredCoder approved these changes

2021-03-17 11:36 UTC, merged